Toss
HifiveProject/feelKo pull request #62
Opened 2024-02-14 11:58 UTC by snow4ram

2024-02-14 12:02 UTC, J-Cheol approved these changes, later dismissed

2024-02-14 13:41 UTC, UJIN901 approved these changes

2024-02-15 01:16 UTC, pth2134 approved these changes

2024-02-15 01:41 UTC, pth2134 requested changes
다른 파트의 dto와 로직 수정 없이 experience에 imageList의 첫번째 imageUrl를 담도록 바꾸는게 더 좋아 보여요

2024-02-15 01:41 UTC, closed without merging